# Generated by Django 3.0.6 on 2020-05-17 04:19

import datetime
from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(default='owner', max_length=256)),
                ('image', models.ImageField(upload_to=items.models.blog_image_file_path)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
