# Generated by Django 3.0.6 on 2020-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
