# Generated by Django 3.0.6 on 2020-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
