# Generated by Django 3.0.6 on 2020-05-17 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200517_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
